project_id = "yjmxzowsrmwvkysfcbyj"

[auth.email]
# Disable email confirmation for basic login
enable_confirmations = false

[functions.generate-video]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false